#!/bin/bash
## Description: Synchronize configuration files
## Usage: sync_initial_configuration
# color
GREEN='\033[0;32m'
NC='\033[0m\n' # set no color and line end

# download file storage "fileadmin" & "public" from staging server
printf "${GREEN}Download initial configuration...${NC}"
rsync -zra \
    --delete \
    ${SSH_USER}@${SSH_HOST}:~/projects/testheadersection_7/shared/staging/ContextConfiguration.php \
    typo3_app/typo3-secure-web/typo3conf;

rsync -zra \
    --delete \
    ${SSH_USER}@${SSH_HOST}:~/projects/testheadersection_7/releases/staging/typo3_app/typo3-secure-web/typo3conf/LocalConfiguration.php \
    typo3_app/typo3-secure-web/typo3conf;

printf "${GREEN}Done${NC}"
